- name: Install Jenkins
  apt:
    deb: http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_2.7.2_all.deb

- name: Install docker-py using pip
  pip:
    name: docker-py
    version: 1.7.0

- name: Append the user jenkins to the group docker
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Creates directory /opt/app/jenkins/docker
  file:
    path: /opt/app/jenkins/docker
    state: directory

- name: Edit the /etc/default/docker file
  lineinfile:
    dest: /etc/default/docker
    line: "DOCKER_OPTS='-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock --restart=false -g /opt/app/jenkins/docker -G jenkins'"

- name: Print Jenkins password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkinsPassword

- debug: msg="{{ jenkinsPassword.stdout_lines }}"

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  sudo: false

- name: Clone the automation-recepies git project
  git:
    repo: https://github.com/luiselizondo/automation-recipes.git
    dest: /tmp/automation-recipes

- name: Build the Docker runner image
  docker_image:
    path: /tmp/automation-recipes
    name: local/runner
    tag: latest

- name: Create first docker slave
  docker_container:
    name: runner-first
    state: started
    image: local/runner
