- name: Copy script file
  copy:
    src: roles/docker_cleanup/files/remove-docker-images-and-stopped-containers
    dest: /opt/remove-docker-images-and-stopped-containers
  tags: docker_cleanup

- name: Grant permissions
  shell: chmod +x /opt/remove-docker-images-and-stopped-containers
  tags: docker_cleanup

- name: Removing unused docker images and stopped containers
  shell: /opt/remove-docker-images-and-stopped-containers
  tags: docker_cleanup
