FROM local/runner
MAINTAINER Luis Elizondo <lelizondo@gmail.com>

RUN apt-get update --fix-missing
RUN apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - \
    && apt-get install -y nodejs build-essential \
    && npm install -g npm@latest \
    && npm install -g mocha node-gyp typings
RUN cd /tmp \
    && curl -O https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
    && tar xvfj phantomjs-2.1.1-linux-x86_64.tar.bz2 \
    && mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs \
    && rm -Rf phantomjs-* \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && apt-get autoremove -y \
    && ln -s /usr/bin/nodejs /usr/local/bin/node \
    && node -v > /etc/nodejs-version

EXPOSE 80
EXPOSE 3000
CMD ["/opt/start-sshd"]
