#!/bin/sh

if [ -n $LIMIT_TO_HOSTS ]; then
  echo "LIMIT_TO_HOSTS is: ${LIMIT_TO_HOSTS}"
fi

HOSTS=`mktemp`
echo "[all_hosts]" > $HOSTS
for HOST in $LIMIT_TO_HOSTS
do
  echo $HOST >> $HOSTS
done

echo "Installing to: $(cat $HOSTS)"

echo "Files in /root/.ssh"
ls /root/.ssh

echo "Doing ping to $HOSTS"
ping -c 2 $HOSTS

echo "Executing test command on host"
ssh -i automation-key root@$HOSTS "echo $HOME"

# TODO: Need to determine the hosts and save them to ansible/hosts or to a temp file
ansible-playbook -i $HOSTS ansible/playbook.yml
