#!/bin/bash

HOSTS_FILE=`mktemp`
function runAnsibleOnHosts() {
  for HOST in $LIMIT_TO_HOSTS
  do
    echo $HOST >> $HOSTS_FILE
  done
}

if [ -n "${LIMIT_TO_HOSTS}" ]; then
  echo "LIMIT_TO_HOSTS is: ${LIMIT_TO_HOSTS}"
fi

if [ -n "${HOSTS_GROUPS}" ]; then
  for HOST_GROUP in $HOSTS_GROUPS
  do
    echo "[${HOST_GROUP}]" >> $HOSTS_FILE
    runAnsibleOnHosts
  done
else
  echo "[all_hosts]" > $HOSTS_FILE
  runAnsibleOnHosts
fi

echo "Installing to: $(cat $HOSTS_FILE)"

# TODO: Need to determine the hosts and save them to ansible/hosts or to a temp file
ansible-playbook -i $HOSTS_FILE ansible/playbook.yml
