#!/bin/bash

set -e
set -x
set -u

IMAGE_NAME=runner

docker build --tag=$IMAGE_NAME .

docker run -it --privileged --rm \
  -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
  -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
  -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
  -e "KEY_PAIR_NAME=${KEY_PAIR_NAME}" \
  -e "SECURITY_GROUP_ID=${SECURITY_GROUP_ID}" \
  -e "SUBNET_ID=${SUBNET_ID}" \
  -v "${HOME}/.ssh:/keys" \
  $IMAGE_NAME /bin/bash
