- name: install apt packages
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - libwww-perl
    - libdatetime-perl
    - unzip
  tags: aws_cloudwatch

- name: Download Cloudwatch Monitoring scripts
  get_url:
    url: http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip
    dest: /tmp/CloudWatchMonitoringScripts-1.2.1.zip
  tags: aws_cloudwatch

- name: Unzip CloudWatch scripts
  unarchive:
    src: /tmp/CloudWatchMonitoringScripts-1.2.1.zip
    dest: /opt
  tags: aws_cloudwatch

- name: Enable CRON
  cron: name="Check Instance Data" minute="5" hour="*" job="/opt/aws-scripts-mon/mon-put-instance-data.pl --mem-util --mem-avail --disk-space-util --swap-util --disk-path=/ --from-cron > /dev/null"
  tags: aws_cloudwatch

- name: Download awslogs-agent-setup
  get_url:
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
    dest: /tmp/awslogs-agent-setup.py
    mode: u+rwx
  tags: aws_cloudwatch

- name: Copy config file
  copy:
    src: roles/aws_cloudwatch/files/cloudwatch-config.cfg
    dest: /etc/cloudwatch-config.cfg
  tags: aws_cloudwatch

- name: Parse the config file
  lineinfile:
    dest: /etc/cloudwatch-config.cfg
    line: log_group_name = {{ cluster_name }}-hosts
    state: present
  tags: aws_cloudwatch

- name: Execute the awslogs-agent-setup
  shell: /tmp/awslogs-agent-setup.py -n -r {{ region }} -c /etc/cloudwatch-config.cfg
  tags: aws_cloudwatch

- name: Start service
  service: name=awslogs state=started
  tags: aws_cloudwatch
