- name: Download awslogs-agent-setup
  get_url:
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
    dest: /tmp/awslogs-agent-setup.py
    mode: u+rwx

- name: Copy config file
  copy:
    src: roles/aws_cloudwatch/files/cloudwatch-config.cfg
    dest: /etc/cloudwatch-config.cfg

- name: Execute the awslogs-agent-setup
  shell: /tmp/awslogs-agent-setup.py -n -r {{ region }} -c /etc/cloudwatch-config.cfg

- name: Start service
  service: name=awslogs state=started
