#!/bin/bash

set -x
set -e

# Prepare the .doctlcfg file with the TOKEN_API variable
echo "access-token: $TOKEN_API" > ${HOME}/.doctlcfg

doctl compute droplet create $NAME --region $REGION --image $IMAGE --size $SIZE --ssh-keys $SSH_KEY_ID
