- name: Install curl
  apt:
    name: curl
    state: present

- name: Install python
  apt:
    name: python
    state: present

- name: Install python pip
  apt:
    name: python-pip
    state: present

- name: Install docker-py using pip
  pip:
    name: docker-py
    version: 1.7.0

- name: Create the Agent Container
  docker_container:
    state: started
    name: ecs-agent
    image: amazon/amazon-ecs-agent:latest
    restart_policy: on-failure
    detach: True
    network_mode: host
    env:
      ECS_LOGLEVEL: info
      ECS_DATADIR: /data
      ECS_CLUSTER: '{{ cluster_name }}'
      ECS_ENABLE_TASK_IAM_ROLE: true
      ECS_AVAILABLE_LOGGING_DRIVERS: ["awslogs"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/ecs/data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro
