- name: Install curl
  yum:
    name: curl
    state: present

- name: Create the Agent Container
  docker_container:
    state: started
    name: ecs-agent
    image: amazon/amazon-ecs-agent:latest
    restart_policy: on-failure
    detach: True
    network_mode: host
    env:
      ECS_LOGFILE: /log/ecs-agent.log
      ECS_LOGLEVEL: info
      ECS_DATADIR: /data
      ECS_CLUSTER: devtest
      ECS_ENABLE_TASK_IAM_ROLE: true
    volumes:
      --volume=/var/run/docker.sock:/var/run/docker.sock
      --volume=/var/log/ecs/:/log
      --volume=/var/lib/ecs/data:/data
      --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro
      --volume=/var/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro

- name: Verify that the agent is running
  shell: curl http://localhost:51678/v1/metadata
