#!/bin/bash

set -x

URL=$GIT_URL
GITHUB_PROJECT_NAME=${GIT_URL#https://github.com}
APP_NAME=$(echo $GITHUB_PROJECT_NAME | sed 's|^.*/||g' | sed 's|.git||g')
echo $APP_NAME

git clone https://github.com/dokku/dokku.git ~/.dokku
cd ~/.dokku
git checkout tags/v0.6.2

ln -s $HOME/.dokku/contrib/dokku_client.sh /usr/local/bin/dokku

echo "Clogning $URL"
git clone $GIT_URL
cd $APP_NAME

echo "Create app $APP_NAME"
dokku apps:create $APP_NAME

echo "Adding remote"
git remote add dokku dokku@$CLIENT_IP:$APP_NAME

echo "Pushing"
git push dokku master
