#!/bin/bash

set -u
set -e

git clone git@github.com:dokku/dokku.git ~/.dokku
cd ~/.dokku
git checkout v0.6.2

ln -s $HOME/.dokku/contrib/dokku_client.sh /usr/local/bin/dokku

git clone $GIT_URL

GITHUB_PROJECT_NAME=${GIT_URL#https://github.com}

APP_NAME=$(echo $GITHUB_PROJECT_NAME | sed 's|^.*/||g' | sed 's|.git||g')
echo $APP_NAME

dokku apps:create $APP_NAME

git remote add dokku dokku@$CLIENT_IP:$APP_NAME

git push dokku master
