#!/bin/bash

set -x
set -u
set -e

# Environment is used as the cluster name
ENVIRONMENT=${ENVIRONMENT}
HOW_MANY_INSTANCES=${HOW_MANY_INSTANCES}
LOAD_BALANCER_NAME=${LOAD_BALANCER_NAME}
CONTAINER_NAME=${CONTAINER_NAME}
CONTAINER_PORT=${CONTAINER_PORT}

# This is temporary
serviceExists="true"

AWS_ROLE=ecsServiceRole
ECS_COMPOSE_FILENAME=ecs-compose.yml

echo "Creating a task definition"
TASK_DEFINITION_RESPONSE_FILE=`mktemp`
ecs-cli compose --file ${ECS_COMPOSE_FILENAME} --project-name ${PROJECT_NAME} --verbose create | tee $TASK_DEFINITION_RESPONSE_FILE

SERVICE_NAME="ecscompose-service-${PROJECT_NAME}"
TASK_DEFINITION_NAME=$(/opt/providers/aws/parse-response-when-creating-a-task-definition $TASK_DEFINITION_RESPONSE_FILE)

if [ "${serviceExists}" = "true" ]; then
    aws ecs update-service --service "${SERVICE_NAME}" --task-definition "${TASK_DEFINITION_NAME}"
else
    aws ecs create-service --service-name "${SERVICE_NAME}" --cluster "${ENVIRONMENT}" --task-definition "$TASK_DEFINITION_NAME" --load-balancers "loadBalancerName=${LOAD_BALANCER_NAME},containerName=${CONTAINER_NAME},containerPort=${CONTAINER_PORT}" --desired-count ${HOW_MANY_INSTANCES} --deployment-configuration "maximumPercent=200,minimumHealthyPercent=50" --role ${AWS_ROLE}
fi
