#!/bin/bash
#
# TODO: Know if the repository is already created and decide
#       There's no sense in having the user create the repository first

set -e
set -u

IMAGE_NAME=$1
AMAZON_REGISTRY_URL=$2

function getDockerLoginCommand() {
  DOCKER_LOGIN_COMMAND=$(aws ecr get-login)
  echo $DOCKER_LOGIN_COMMAND
}

docker build --tag=${IMAGE_NAME}:${BUILD_NAME} .

docker tag ${IMAGE_NAME} ${AMAZON_REGISTRY_URL}/${IMAGE_NAME}:${BUILD_NUMBER}

exec getDockerLoginCommand

docker push ${AMAZON_REGISTRY_URL}/${IMAGE_NAME}
