#!/bin/bash
#
# TODO: Know if the repository is already created and decide
#       There's no sense in having the user create the repository first

set -x

export DOCKER_HOST="tcp://0.0.0.0:2375"
DOCKER_OPTS="-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375"
docker daemon ${DOCKER_OPTS} &

echo "Sleeping for 10 seconds"
sleep 10

counter=0
# Wait a minute for docker to start
while [ $counter -lt 60 ]; do
  if [ -e /var/run/docker.sock ]; then
  	echo "Docker is running"
  	break
  else
	  echo "Testing if docker is running"
	  counter=$(($counter+1))
	  sleep 1
  fi
done

if [ $counter -eq 60 ] ; then
    echo "Docker is not running after one minute, exiting"
    exit 1
fi

set -e
set -u

IMAGE_NAME=$1
AMAZON_REGISTRY_URL=$2
ENVIRONMENT=$3

function getDockerLoginCommand() {
  DOCKER_LOGIN_COMMAND=$(aws ecr get-login)
  echo $DOCKER_LOGIN_COMMAND
}

docker build --tag=${IMAGE_NAME}:${BUILD_NUMBER} .

docker tag ${IMAGE_NAME}:${BUILD_NUMBER} ${AMAZON_REGISTRY_URL}/${IMAGE_NAME}:${BUILD_NUMBER}

dockerLoginCommand=$(getDockerLoginCommand)
eval $dockerLoginCommand

docker push ${AMAZON_REGISTRY_URL}/${IMAGE_NAME}:${BUILD_NUMBER}
