#!/bin/bash

INSTANCE_ID=$1

export AWS_DEFAULT_OUTPUT="json"

OUTPUT=`mktemp`

aws ec2 describe-instance-status \
  --instance-ids $INSTANCE_ID > $OUTPUT

result=$(/opt/providers/aws/parse-get-instance-status-result $OUTPUT)
echo $result
