#!/usr/bin/env python3

import sys
import json
from pprint import pprint

def main():
  fileName = sys.argv[1:][0]
  with open(fileName) as jsonFile:
    data = json.load(jsonFile)

    reservations = data["Reservations"]
    print(reservations[0]["Instances"][0]["PrivateIpAddress"], end=" ")

if __name__ == "__main__":
  main()
