#!/usr/bin/env python3

import sys
import json
from pprint import pprint

def main():
  fileName = sys.argv[1:][0]
  with open(fileName) as jsonFile:
    data = json.load(jsonFile)

    loadBalancers = data["LoadBalancers"]
    print(loadBalancers[0]["LoadBalancerArn"], end="")

if __name__ == "__main__":
  main()
