#!/usr/bin/env python3

import sys
import json
from pprint import pprint

def main():
  fileName = sys.argv[1:][0]
  with open(fileName) as jsonFile:
    data = json.load(jsonFile)

    targetGroups = data["TargetGroups"]
    print(targetGroups[0]["TargetGroupArn"], end="")

if __name__ == "__main__":
  main()
