#!/bin/bash

set -u
set -e

echo "THIS SCRIPT IS DEPRECATED"

TASK_NAME=$1
IMAGE_TAG=$2

ORIGINAL_FILE=templates/${TASK_NAME}.json

NEW_FILE=/tmp/${TASK_NAME}-processed.json

cat ${ORIGINAL_FILE} | sed 's/@@IMAGE_TAG@@/${TASK_NAME}/g' > ${NEW_FILE}

aws ecs register-task-definition \
  --cli-input-json file://${NEW_FILE}
