#!/bin/bash

set -x
set -u
set -e

privateIPs=${HOSTS_IPS}
PRIVATE_KEY_NAME=${PRIVATE_KEY_NAME}
USERNAME=${USERNAME}

CONTAINER_NAME=$1
IMAGE=$2
TASKS="docker_deploy"

function errorTrap {
  status=$?
  echo "ERROR: Command exited with status $status."
}

HOSTS_FILE=`mktemp`
function runAnsibleOnHosts() {
  hosts=$1

  echo "[aws_ecs_cluster]" > $HOSTS_FILE
  for HOST in $hosts
  do
    echo $HOST >> $HOSTS_FILE
  done
}

runAnsibleOnHosts "${privateIPs}"

echo "Running custom task docker_deploy to: $(cat $HOSTS_FILE)"
ansible-playbook \
--user=${USERNAME} \
--private-key=/keys/${PRIVATE_KEY_NAME} \
--extra-vars="container_name=${CONTAINER_NAME} image=${IMAGE}" \
--verbose \
--become \
-c paramiko \
-t "${TASKS}" \
--inventory-file=$HOSTS_FILE /opt/ansible/docker-deploy.yml
