#!/bin/bash

set -x
set -u
set -e

TASKS="docker_cleanup"
CLUSTER_NAME=$1
PRIVATE_KEY_NAME=$2
USERNAME=$3
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

function errorTrap {
  status=$?
  echo "ERROR: Command exited with status $status."
}

HOSTS_FILE=`mktemp`
function runAnsibleOnHosts() {
  hosts=$1

  echo "[aws_ecs_cluster]" > $HOSTS_FILE
  for HOST in $hosts
  do
    echo $HOST >> $HOSTS_FILE
  done
}

function getHostsToConfigure() {
  PRIVATE_IPS=$(aws ec2 describe-instances --filters "Name=tag:Environment,Values=${CLUSTER_NAME}" "Name=instance-state-name,Values=running" --query 'Reservations[*].Instances[*].PrivateIpAddress' --output=text)

  HOSTS=""
  for private in $PRIVATE_IPS; do
    HOSTS="${HOSTS}${private},"
  done

  echo "${HOSTS%?}"
}

HOSTS_TO_CONFIGURE=$(getHostsToConfigure)
runAnsibleOnHosts "${HOSTS_TO_CONFIGURE}"

echo "Running custom task docker_cleanup to: $(cat $HOSTS_FILE)"
ansible-playbook \
--user=${USERNAME} \
--private-key=/keys/${PRIVATE_KEY_NAME} \
--extra-vars="cluster_name=${CLUSTER_NAME} region=${AWS_DEFAULT_REGION}" \
--verbose \
--become \
-c paramiko \
-t "${TASKS}" \
--inventory-file=$HOSTS_FILE /opt/ansible/docker-cleanup-playbook.yml
