#!/bin/bash

set -x
set -e
set -u

USER=$1
HOST_IP=$2

ssh -o StrictHostKeyChecking=no -i ~/.ssh/automation-key $USER@$HOST_IP <<EOF
touch $HOME/.ssh/config
echo "Host *" >> $HOME/.ssh/config
echo "StrictHostKeyChecking no" >> $HOME/.ssh/config
echo "UserKnownHostsFile=/dev/null" >> $HOME/.ssh/config
EOF
