#!/bin/bash

# Start docker in daemon mode
echo "Starting docker"
set -x

which dockerd

dockerd

counter=0
# Wait a minute for docker to start
while [ $counter -lt 60 ]; do
  if [ -e /var/run/docker.sock ]; then
  	echo "Docker is running"
  	break
  else
	  echo "Testing if docker is running"
	  counter=$(($counter+1))
	  sleep 1
  fi
done

if [ $counter -eq 60 ] ; then
    echo "Docker is not running after one minute, exiting"
    exit 1
fi
