#!/bin/bash

TAG=$1
DOCKERFILE=$2
FILE_TO_INJECT=$3

DOCKERFILE_INJECTED=`mktemp`

cat $DOCKERFILE > $DOCKERFILE_INJECTED
cat $FILE_TO_INJECT >> $DOCKERFILE_INJECTED

cp $DOCKERFILE_INJECTED ./Dockerfile.temp

docker build -f Dockerfile.temp --tag $TAG .
rm Dockerfile.temp
