- name: Add apt key
  apt_key:
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Installing apt-transport-https and ca-certificates
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add docker repository
  lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    line: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    insertafter: 'EOF'
    state: present
    create: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Running apt-get update
  apt:
    update_cache: yes

- name: Purge lxc-docker
  apt:
    pkg: 'lxc-docker'
    purge: yes
    state: absent

- name: Install docker-engine
  apt:
    pkg: 'docker-engine'
    state: present
