- name: install common software
  hosts: all_hosts
  become: true
  become_user: root
  roles:
    - common

- name: install docker
  hosts: docker_hosts
  become: true
  become_user: root
  roles:
    - docker_xenial

- name: install dokku
  hosts: dokku_hosts
  vars:
    - dokku_version: "0.5.8"
    - dokku_vhost: "{{ ansible_hostname }}"
    - dokku_plugins: []
    - sshkeys: []
  become: true
  become_user: root
  roles:
    - dokku

- name: install jenkins
  hosts: jenkins_hosts
  become: true
  become_user: root
  gather_facts: no
  roles:
    - common
    - docker_xenial
    - jenkins
  pre_tasks:
    - raw: sudo apt-get update --fix-missing
    - raw: sudo apt-get -y install python-simplejson python-pip
