- name: install common software
  hosts: all_hosts
  user: root
  become_user: root
  roles:
    - all

- name: install docker
  hosts: docker_hosts
  user: root
  become_user: root
  roles:
    - docker

- name: install dokku
  hosts: dokku_hosts
  vars:
    - dokku_version: "0.5.8"
    - dokku_vhost: "{{ ansible_hostname }}"
    - dokku_plugins: []
    - sshkeys: []
  user: root
  become_user: root
  roles:
    - dokku
